version: '3.8'
services:
    
    WebFrontend:
       container_name: php-apache
       image: php:7.0-apache
       build:
          context: .
          dockerfile: Dockerfile
       depends_on:
         - mySQL
       volumes:
          - .:/var/www/html/
       ports:
         - 8000:80

    mySQL:
        container_name: mySQL
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: MYSQL_DATABASE
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
        ports:
            - "9906:3306"

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      ports:
          - '8080:80'
      restart: always
      environment:
          PMA_HOST: mySQL
      depends_on:
          - mySQL   
          
    mongo:
      image: mongo
      container_name: mongoDB
      environment:
          - MONGO_INITDB_ROOT_USERNAME=root
          - MONGO_INITDB_ROOT_PASSWORD=password
      restart: unless-stopped
      ports:
        - "27017:27017"
      volumes:
        - .:/data/db
    
    mongo-express:
      image: mongo-express
      container_name: mexpress
      environment:
        - ME_CONFIG_MONGODB_ADMINUSERNAME=root
        - ME_CONFIG_MONGODB_ADMINPASSWORD=password
        - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017
      links:
        - mongo
      restart: unless-stopped
      ports:
        - "8081:8081" 
          